export type {
  ActiveCasesCardDto,
  ActivitiesDto,
  ActivitiesDashboardDto,
  ActivityActorDto,
  ActivityItemDto,
  ActivityTargetDto,
  BillableHoursCardDto,
  BillableHoursPeriodsDto,
  CaseMixDto,
  CaseMixSliceDto,
  CaseOverviewStatsDto,
  ChartsDto,
  ChartSeriesPointDto,
  ClientsCardDto,
  DashboardAlertsDto,
  DashboardResponseDto,
  DashboardUserDto,
  DashboardWorkspaceDto,
  DeadlineItemDto,
  DeadlinesDto,
  DeadlinesDashboardDto,
  DeadlineWindowsDto,
  GreetingDto,
  HearingItemDto,
  HearingsDto,
  HearingsDashboardDto,
  NotificationSummaryDto,
  OverviewDto,
  RevenueBreakdownDto,
  RevenueCardDto,
  RevenueDashboardDto,
  RevenueGrowthDto,
  RevenueMonthPointDto,
  RevenuePeriodsDto,
  TeamDto,
  TeamMemberDto,
  TeamRoleCountsDto,
  WinRateCardDto,
} from './dashboard-response.dto';


