export type {
  ActiveCasesCardDto,
  ActivitiesDto,
  ActivityItemDto,
  BillableHoursCardDto,
  CaseMixDto,
  ChartsDto,
  ChartSeriesPointDto,
  ClientsCardDto,
  DashboardResponseDto,
  DashboardUserDto,
  DashboardWorkspaceDto,
  DeadlineItemDto,
  DeadlinesDto,
  GreetingDto,
  HearingItemDto,
  HearingsDto,
  OverviewDto,
  RevenueBreakdownDto,
  RevenueCardDto,
  RevenueMonthPointDto,
  TeamDto,
  TeamMemberDto,
  WinRateCardDto,
} from './dashboard-response.dto';
