export const endpoints = {
  health: '/health',
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
  },
  dashboard: '/api/dashboard',
  documents: {
    root: '/api/documents',
    byId: (id: string) => `/api/documents/${id}`,
    file: (id: string) => `/api/documents/${id}/file`,
  },
  clients: {
    root: '/api/clients',
    byId: (id: string) => `/api/clients/${id}`,
  },
  cases: {
    root: '/api/cases',
    stats: '/api/cases/stats',
    byId: (id: string) => `/api/cases/${id}`,
    status: (id: string) => `/api/cases/${id}/status`,
    bulk: '/api/cases/bulk',
  },
  hearings: {
    root: '/api/hearings',
    calendar: '/api/hearings/calendar',
    byId: (id: string) => `/api/hearings/${id}`,
    reschedule: (id: string) => `/api/hearings/${id}/reschedule`,
    outcome: (id: string) => `/api/hearings/${id}/outcome`,
  },
  deadlines: {
    root: '/api/deadlines',
    byId: (id: string) => `/api/deadlines/${id}`,
  },
  billing: {
    invoices: '/api/billing/invoices',
    invoicesSummary: '/api/billing/invoices/summary',
    invoice: (id: string) => `/api/billing/invoices/${id}`,
    invoiceSend: (id: string) => `/api/billing/invoices/${id}/send`,
    invoiceVoid: (id: string) => `/api/billing/invoices/${id}/void`,
    invoiceMarkPaid: (id: string) => `/api/billing/invoices/${id}/mark-paid`,
    payments: '/api/billing/payments',
    payment: (id: string) => `/api/billing/payments/${id}`,
    manualRevenue: '/api/billing/manual-revenue',
    billableHours: '/api/billing/billable-hours',
    billableHour: (id: string) => `/api/billing/billable-hours/${id}`,
    // Legacy path constants kept for backwards compat
    invoicePdf: (id: string) => `/api/billing/invoices/${id}/pdf`,
    invoiceDuplicate: (id: string) => `/api/billing/invoices/${id}/duplicate`,
    paymentRefund: (id: string) => `/api/billing/payments/${id}/refund`,
    summary: '/api/billing/invoices/summary',
    projection: '/api/billing/projection',
    insights: '/api/billing/insights',
    actions: '/api/billing/actions',
    outstanding: '/api/billing/outstanding',
  },
  reports: {
    root: '/api/reports',
    dashboard: '/api/reports/dashboard',
    library: '/api/reports/library',
    librarySummary: '/api/reports/library/summary',
    byId: (id: string) => `/api/reports/${id}`,
    preview: '/api/reports/preview',
    generate: '/api/reports/generate',
    run: (id: string) => `/api/reports/${id}/run`,
    duplicate: (id: string) => `/api/reports/${id}/duplicate`,
    rename: (id: string) => `/api/reports/${id}/rename`,
    schedule: (id: string) => `/api/reports/${id}/schedule`,
    share: (id: string) => `/api/reports/${id}/share`,
    exportPdf: (id: string) => `/api/reports/${id}/export/pdf`,
    exportExcel: (id: string) => `/api/reports/${id}/export/excel`,
    exportCsv: (id: string) => `/api/reports/${id}/export/csv`,
    analytics: '/api/reports/analytics',
  },
  users: {
    root: '/api/users',
    summary: '/api/users/summary',
    byId: (id: string) => `/api/users/${id}`,
    invite: '/api/users',
    invitations: '/api/users/invitations',
    activate: (id: string) => `/api/users/${id}`,
    suspend: (id: string) => `/api/users/${id}`,
    resetPassword: (id: string) => `/api/users/${id}/reset-password`,
    importCsv: '/api/users/import',
    roles: '/api/users/roles',
    rolesSummary: '/api/users/roles/summary',
    role: (id: string) => `/api/users/roles/${id}`,
    rolePermissions: (id: string) => `/api/users/roles/${id}/permissions`,
  },
  activities: {
    root: '/api/activities',
  },
} as const
