export const endpoints = {
  health: '/health',
  auth: {
    register: '/api/auth/register',
    login: '/api/auth/login',
  },
  dashboard: '/api/dashboard',
  documents: {
    root: '/api/documents',
    byId: (id: string) => `/api/documents/${id}`,
    file: (id: string) => `/api/documents/${id}/file`,
  },
  billing: {
    invoices: '/api/billing/invoices',
    invoice: (id: string) => `/api/billing/invoices/${id}`,
    invoicePdf: (id: string) => `/api/billing/invoices/${id}/pdf`,
    invoiceSend: (id: string) => `/api/billing/invoices/${id}/send`,
    invoiceDuplicate: (id: string) => `/api/billing/invoices/${id}/duplicate`,
    invoiceVoid: (id: string) => `/api/billing/invoices/${id}/void`,
    invoiceMarkPaid: (id: string) => `/api/billing/invoices/${id}/mark-paid`,
    payments: '/api/billing/payments',
    payment: (id: string) => `/api/billing/payments/${id}`,
    paymentRefund: (id: string) => `/api/billing/payments/${id}/refund`,
    summary: '/api/billing/summary',
    projection: '/api/billing/projection',
    insights: '/api/billing/insights',
    actions: '/api/billing/actions',
    outstanding: '/api/billing/outstanding',
  },
  reports: {
    root: '/api/reports',
    dashboard: '/api/reports/dashboard',
    library: '/api/reports/library',
    librarySummary: '/api/reports/library/summary',
    byId: (id: string) => `/api/reports/${id}`,
    preview: '/api/reports/preview',
    generate: '/api/reports/generate',
    run: (id: string) => `/api/reports/${id}/run`,
    duplicate: (id: string) => `/api/reports/${id}/duplicate`,
    rename: (id: string) => `/api/reports/${id}/rename`,
    schedule: (id: string) => `/api/reports/${id}/schedule`,
    share: (id: string) => `/api/reports/${id}/share`,
    exportPdf: (id: string) => `/api/reports/${id}/export/pdf`,
    exportExcel: (id: string) => `/api/reports/${id}/export/excel`,
    exportCsv: (id: string) => `/api/reports/${id}/export/csv`,
    analytics: '/api/reports/analytics',
  },
  users: {
    root: '/api/users',
    summary: '/api/users/summary',
    byId: (id: string) => `/api/users/${id}`,
    invite: '/api/users/invite',
    invitations: '/api/users/invitations',
    activate: (id: string) => `/api/users/${id}/activate`,
    suspend: (id: string) => `/api/users/${id}/suspend`,
    resetPassword: (id: string) => `/api/users/${id}/reset-password`,
    importCsv: '/api/users/import',
    roles: '/api/users/roles',
    rolesSummary: '/api/users/roles/summary',
    role: (id: string) => `/api/users/roles/${id}`,
    rolePermissions: (id: string) => `/api/users/roles/${id}/permissions`,
  },
} as const
